import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // * Este layout impactara en todas nuestras pagnoas de la aplicación
  // * solo modificar cuando se necesite modificar la estructura del layuot a nivel global
  return (
    <html lang="en">
      <body className={inter.className}>
        <p>Root Layout</p>
        {children}
      </body>
    </html>
  )
}
